source 'http://rubygems.org'

gem 'rack'
gem 'rack-rewrite'
gem 'thin'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-subdomain'
gem 'pg'
gem 'sequel', '3.48.0'
gem 'sequel_pg'
gem 'sanitize'
gem 'coffee-script'
gem 'slim', '1.3.8'
gem 'mail'
gem 'riddle'
gem 'flickraw-cached'
gem 'dalli'
gem 'kgio' # speed up dalli
gem 'aws-s3'
gem 'rmagick'
